
apiVersion: v1
kind: Service
metadata:
  name: customer-app-service
  labels:
    app: customer-app
spec:
  type: LoadBalancer  # Change the type to LoadBalancer
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: customer-app
