apiVersion: v1
kind: Service
metadata:
  name: customer-app-service
  labels:
    app: customer-app
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 31000
  selector:
    app: customer-app
