# This is a basic workflow to help you get started with Actions
name: CI-build-and-push-image-for-dotnetapp

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
    paths-ignore:
      - README.md
      - .vscode/**
      - .gitignore
  pull_request:
    branches: [ main ]
    paths-ignore:
      - README.md
      - .vscode/**
      - .gitignore
      
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
 docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./LearnSmartCoding.API/Dockerfile
          push: true
          tags: chandu5562/dockerfordotnetapi:latest,chandu5562/dockerfordotnetapi:${{ github.run_number }}
 deploy-to-eks:
  needs: docker
  runs-on: ubuntu-latest
  steps:
    - name: Checkout repository
      uses: actions/checkout@v2  # Use the latest version of actions/checkout

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1  # Replace with your desired AWS region

    - name: Install kubectl
      run: |
        sudo apt-get update -q
        sudo apt-get install -y kubectl

    - name: Configure kubectl for EKS
      run: aws eks --region us-east-1 update-kubeconfig --name ed-eks-01

    - name: Deploy to EKS
      run: |
        kubectl apply -f LearnSmartCoding.OrderProcessor/deployment.yaml
        kubectl apply -f LearnSmartCoding.OrderProcessor/services.yaml
      # Add any additional deployment steps or commands here
